server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  server:
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

