server:
  port: 8081
spring:
  application:
    name: eureka-client-b
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
    register-with-eureka: true #是否向服务中心注册
    fetch-registry: true #是否拉去服务列表到本地
    registry-fetch-interval-seconds: 10 #拉去服务列表间隔
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

